# Generated by Django 3.2.19 on 2023-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('name', models.CharField(db_column='FieldName', max_length=50, primary_key=True, serialize=False)),
                ('adjustability', models.CharField(db_column='Adjustibility', max_length=1)),
                ('usage', models.CharField(db_column='Usage', max_length=200)),
            ],
            options={
                'db_table': 'tblControls',
                'managed': False,
            },
        ),
    ]
